#!/bin/bash

if which Xvfb > /dev/null 2> /dev/null;
then
	true
else
	echo dirtconsole: Xvfb not found!
	exit 1
fi

if which xvfb-run > /dev/null 2> /dev/null;
then
	true
else
	echo dirtconsole: xvfb-run not found!
	exit 1
fi

LISTEN_PORT=500

while [ $LISTEN_PORT != 600 ]
do

        LOCK_FILE=/tmp/.X${LISTEN_PORT}-lock

        if [ ! -f $LOCK_FILE ]
        then
                exec xvfb-run -n $LISTEN_PORT `dirname $0`/Dirt --console $*
        fi

        LISTEN_PORT=$(($LISTEN_PORT+1))

done
