#!/bin/bash

if which Xvfb > /dev/null 2> /dev/null;
then
	true
else
	echo dirtconsole: Xvfb not found!
	exit 1
fi

if which xvfb-run > /dev/null 2> /dev/null;
then
	true
else
	echo dirtconsole: xvfb-run not found!
	exit 1
fi

exec xvfb-run `dirname $0`/Dirt --console $*
