ifeq (,$(WXCONFIG))
        WXCONFIG=wx-config
endif

WX_BASENAME = $(shell $(WXCONFIG) --basename 2> /dev/null)
ifeq (,$(WX_BASENAME))
        WX_BASENAME = $(shell $(WXCONFIG) --libs | tr ' ' '\n' | grep wx_)
endif
