#!/bin/bash -e

if [ "`uname -s`" == "Darwin" -a "$1" == "" ]
then

	dist/Dirt.app/Contents/MacOS/Dirt

else

	BIN="java"
	OPTIONS="-jar dist/Dirt.jar"
	
	case "$1"
	in
		
		--debug)
			shift
			BIN="jdb"
			OPTIONS="-classpath lib/common/jline-0.9.91.jar:build/main-scratch au.com.gslabs.dirt.Dirt"
			;;
			
		--applet)
			shift
			BIN="appletviewer"
			OPTIONS="dist/dirt_applet.html"
			;;
		
		*)
			if [ "`uname -s`" == "Darwin" ]
			then
				if [ "$1" == "--profile" ]
				then
					OPTIONS="$OPTIONS -Dapple.laf.useScreenMenuBar=true -Xdock:name=Dirt"
				else
					BIN="dist/Dirt.app/Contents/MacOS/Dirt"
					OPTIONS=""
				fi
			fi
			if [ "$1" == "--profile" ]
			then
				shift
				PROFILER_LIB_DIR=`echo /Applications/YourKit\ Java\ Profiler\ *.app/bin/mac`
				if [ ! -d "$PROFILER_LIB_DIR" ]
				then
					echo YourKit Java Profiler not found. >&2
					exit 1;
				fi
				export DYLD_LIBRARY_PATH="$PROFILER_LIB_DIR"
				OPTIONS="$OPTIONS -agentlib:yjpagent"
			fi
			;;
		
	esac
	
	$BIN $OPTIONS "$@"
	
fi
