/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_com_gslabs_dirt_lib_util_jni_Win32 */

#ifndef _Included_au_com_gslabs_dirt_lib_util_jni_Win32
#define _Included_au_com_gslabs_dirt_lib_util_jni_Win32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_com_gslabs_dirt_lib_util_jni_Win32
 * Method:    getMyFullName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_com_gslabs_dirt_lib_util_jni_Win32_getMyFullName
  (JNIEnv *, jobject);

/*
 * Class:     au_com_gslabs_dirt_lib_util_jni_Win32
 * Method:    getAppDataPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_com_gslabs_dirt_lib_util_jni_Win32_getAppDataPath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
